version: '3.1'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: ""  
      MYSQL_DATABASE: BloggingSystem   
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - phpmyadmin-net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-container
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    ports:
      - 8080:80
    networks:
      - phpmyadmin-net

networks:
  phpmyadmin-net:
    driver: bridge

volumes:
  mysql-data:
