name: Node.js CI with Docker

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      # إعداد خدمة Docker (قاعدة بيانات MySQL مثلاً)
      mysql:
        image: mysql:5.7
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: blogging_system
        options: --health-cmd="mysqladmin ping --silent" --health-start-period=10s --health-retries=5
        # تأكد من أن الخدمة جاهزة للاتصال قبل تنفيذ الاختبارات

    steps:
      - uses: actions/checkout@v4

      # Set up Node.js version
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      # Set environment variables for DB connection
      - name: Set up environment variables
        run: |
          echo "DB_HOST=127.0.0.1" >> $GITHUB_ENV
          echo "DB_USER=root" >> $GITHUB_ENV
          echo "DB_PASSWORD=rootpassword" >> $GITHUB_ENV
          echo "DB_NAME=blogging_system" >> $GITHUB_ENV

      # Install dependencies
      - run: npm ci

      # Build the project if a build step is present
      - run: npm run build --if-present

      # Run tests (فحص الاتصال بقاعدة البيانات أثناء الاختبارات)
      - run: npm test
